@echo off

echo Calling Batch Files for Data Insertion
pause

call C:\SNF_SQL\BATCH\DATA_INSERTION\COPY_INTO_FF_GAMES_VICTOR.bat
call C:\SNF_SQL\BATCH\DATA_INSERTION\MERGE_INTO_STG_GAMES_VICTOR.bat
call C:\SNF_SQL\BATCH\DATA_INSERTION\MERGE_INTO_STG_GAMES_ADD_VICTOR.bat
call C:\SNF_SQL\BATCH\DATA_INSERTION\MERGE_INTO_DIM_GENRE_VICTOR.bat
call C:\SNF_SQL\BATCH\DATA_INSERTION\MERGE_INTO_DIM_PLATFORM_VICTOR.bat
call C:\SNF_SQL\BATCH\DATA_INSERTION\MERGE_INTO_DIM_PRODUCT_VICTOR.bat
call C:\SNF_SQL\BATCH\DATA_INSERTION\MERGE_INTO_DIM_PUBLISHER_VICTOR.bat
call C:\SNF_SQL\BATCH\DATA_INSERTION\MERGE_INTO_DIM_REGION_VICTOR.bat
call C:\SNF_SQL\BATCH\DATA_INSERTION\MERGE_INTO_DIM_TIME_VICTOR.bat
call C:\SNF_SQL\BATCH\DATA_INSERTION\MERGE_INTO_FACT_GAMES_VICTOR.bat

echo All batch files executed successfully
pause
