EXECUTE IMMEDIATE $$

CREATE OR REPLACE TABLE "UNIVERSITY_BLUETAB"."SOLUTION_TIER"."DIM_TIME_VICTOR"(
	"Id_Year" INT IDENTITY(1,1) PRIMARY KEY,
    "Year_Num" VARCHAR(4),
    "CreatedOn" TIMESTAMP_NTZ,
    "CreatedBy" VARCHAR(20)
    );

$$;