EXECUTE IMMEDIATE $$

CREATE OR REPLACE TABLE "UNIVERSITY_BLUETAB"."SOLUTION_TIER"."DIM_PRODUCT_VICTOR"(
	"Id_Product" INT IDENTITY(1,1) PRIMARY KEY,
    "Nm_Product" VARCHAR (100),
    "CreatedOn" TIMESTAMP_NTZ,
    "CreatedBy" VARCHAR(20)
    );

$$;