EXECUTE IMMEDIATE $$

CREATE OR REPLACE TABLE "UNIVERSITY_BLUETAB"."SOLUTION_TIER"."DIM_GENRE_VICTOR"(
	"Id_Genre" INT IDENTITY(1,1) PRIMARY KEY,
    "Nm_Genre" VARCHAR(100),
    "CreatedOn" TIMESTAMP_NTZ,
    "CreatedBy" VARCHAR(20)
    );

$$;