EXECUTE IMMEDIATE $$

CREATE OR REPLACE TABLE "UNIVERSITY_BLUETAB"."SOLUTION_TIER"."DIM_REGION_VICTOR"(
	"Id_Region" INT IDENTITY(1,1) PRIMARY KEY,
    "Nm_Region" VARCHAR (100),
    "CreatedOn" TIMESTAMP_NTZ,
    "CreatedBy" VARCHAR(20)
    );

$$;