EXECUTE IMMEDIATE $$

CREATE OR REPLACE TABLE "UNIVERSITY_BLUETAB"."SOLUTION_TIER"."DIM_PUBLISHER_VICTOR"(
	"Id_Publisher" INT IDENTITY(1,1) PRIMARY KEY,
    "Nm_Publisher" VARCHAR (100),
    "CreatedOn" TIMESTAMP_NTZ,
    "CreatedBy" VARCHAR(20)
    );

$$;