EXECUTE IMMEDIATE $$

CREATE OR REPLACE TABLE "UNIVERSITY_BLUETAB"."SOLUTION_TIER"."DIM_PLATFORM_VICTOR"(
	"Id_Platform" INT IDENTITY(1,1) PRIMARY KEY,
    "Nm_Platform" VARCHAR (100),
    "CreatedOn" TIMESTAMP_NTZ,
    "CreatedBy" VARCHAR(20)
    );

$$;